export default {
    SAVE_USER: "SAVE_USER",
    SAVE_IMAGE: "SAVE_IMAGE",
    GET_COUNTRIES: "GET_COUNTRIES_ACTION",
    GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
    GET_COUNTRIES_PENDING: "GET_COUNTRIES_PENDING"
}